name: CI/CD for WordPress on K8s

on:
  push:
    branches:
      - main   # run pipeline on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-k8s
        docker build -t $IMAGE_NAME:${{ github.sha }} .
        docker push $IMAGE_NAME:${{ github.sha }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/wordpress-k8s:${{ github.sha }}
        kubectl set image deployment/wordpress wordpress=$IMAGE_NAME -n wordpress
        kubectl rollout status deployment/wordpress -n wordpress

